name: 'PR Bundle Analyzer'
description: 'Github action to analyse your build bundle and show stats difference with the Base branch.'
author: 'BharatPe'
inputs:
  target_folder:
    description: 'cli command for installing dependencies ex npm install'
    required: true
    default: 'src/assets'
  thrashold_size:
    description: 'cli command for building repository ex npm run build'
    required: true
    default: '100'
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
outputs:
  size:
    description: 'Build Size Difference'
branding:
  icon: 'hard-drive'
  color: 'blue'