name: 'PR Bundle Analyzer - 1'
description: 'Github action to analyse your build bundle and show stats difference with the Base branch.'
author: 'BharatPe'
inputs:
  target_folder:
    description: 'output path for the build package'
    required: true
    default: 'src/assets'
  thrashold_size:
    description: 'Branch on which your feature branch will get merge ex. main'
    required: true
    default: 10
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
